export const GET_HEADLINE_START = "GET_HEADLINE_START";
export const GET_HEADLINE_SUCCESS = "GET_HEADLINE_SUCCESS";
export const GET_HEADLINE_FAILD = "GET_HEADLINE_FAILD";

export const GET_AD_START = "GET_AD_START";
export const GET_AD_SUCCESS = "GET_AD_SUCCESS";
export const GET_AD_FAILD = "GET_AD_FAILD";

export const GET_LIST_START = "GET_LIST_START";
export const GET_LIST_SUCCESS = "GET_LIST_SUCCESS";
export const GET_LIST_FAILD = "GET_LIST_FAILD";
